In [3]:
import pandas as pd
import numpy as np
#import py_pcha
#from py_pcha import PCHA
import matplotlib.pyplot as plt
from numpy.matlib import repmat

In [ ]:
data=pd.read_csv("/Users/markomiholjcic/Documents/GitHub/ArchetypalAnalysis/data/us_states_covid19_daily.csv")
data

In [ ]:
data=pd.read_csv("/Users/u0984549/Documents/GitHub/ArchetypalAnalysis/data/us_states_covid19_daily.csv")
data

Data for 50 states, DC, and 5 territories on December 6, 2020. Select states and territories with missing values were removed. 

In [ ]:
dec6 = data.loc[data['date'] == 20201206]
dec6 = dec6[['positive','negative','totalTestResults','recovered', 'death']]
dec6 = dec6.dropna()
dec6

In [ ]:
dec6.to_csv('/Users/markomiholjcic/Documents/GitHub/ArchetypalAnalysis/data/COVID19.csv', index = False)

In [ ]:
dec6.to_csv('/Users/u0984549/Documents/GitHub/ArchetypalAnalysis/data/COVID19.csv', index = False)

In [13]:
U = np.array([1,2,3])
X = np.array([[2,3,4,5], [5,6,7,8], [1,4,5,6]])

print(X)
print(X.T)

#(X[:, U] * X[:, U])

[[2 3 4 5]
 [5 6 7 8]
 [1 4 5 6]]
[[2 5 1]
 [3 6 4]
 [4 7 5]
 [5 8 6]]


In [14]:
np.dot(X, X.T)

array([[ 54,  96,  64],
       [ 96, 174, 112],
       [ 64, 112,  78]])

In [19]:
repmat(np.mat(np.diag(X)).T, 1, 5)

matrix([[2, 2, 2, 2, 2],
        [6, 6, 6, 6, 6],
        [5, 5, 5, 5, 5]])

In [25]:
t = np.diag(X)
print(t)
np.where(t != 2)[0]

[2 6 5]


array([1, 2])

In [21]:
repmat(np.diag(X), 5, 1)

array([[2, 6, 5],
       [2, 6, 5],
       [2, 6, 5],
       [2, 6, 5],
       [2, 6, 5]])

In [ ]:
X[:,U]*X[:,U]

In [27]:
ind_t = 2

In [30]:
X

array([[2, 3, 4, 5],
       [5, 6, 7, 8],
       [1, 4, 5, 6]])

In [42]:
X[[ind_t],:] * X[ind_t]

array([[ 1, 16, 25, 36]])

In [40]:
np(X + X[ind_t])

TypeError: 'module' object is not callable

In [28]:
np.lib.scimath.sqrt(X + X[ind_t])

array([[1.73205081, 2.64575131, 3.        , 3.31662479],
       [2.44948974, 3.16227766, 3.46410162, 3.74165739],
       [1.41421356, 2.82842712, 3.16227766, 3.46410162]])

In [ ]:
Kt = np.array([[1,2], [5,6], [8,9]])
Kt = pd.DataFrame(Kt)
Kt.to_csv('/Users/markomiholjcic/Documents/GitHub/ArchetypalAnalysis/data/small.csv', index = False)

In [ ]:
e = np.ones((4, 1))
e

In [ ]:
CtXtXC = [2,3]
S = [3,4]
XCtX = [1,1]
SST = 5
J = 5
g = (np.dot(CtXtXC, S) - XCtX) / (SST / J)
g

In [ ]:
a = np.arange(10)
a.clip(min=5)

In [ ]:
a = range(2)
print(a)

In [ ]:
X = np.matrix([[1, 2, 3],
    [4, 5, 6], [7,8,9]])
U = [0,1,2]
print(U)
print(X)
print(X[:, U])

In [ ]:
np.sum(np.multiply(X[:, U],X[:, U]))

In [ ]:
[int(np.ceil(len(U) * np.random.rand()))]

In [ ]:
noc = 3
I = [1,2]
i = [3]
j = 3

In [ ]:
len(I)

In [ ]:
Kt = np.array([[1,2], [5,6], [8,9]])
print(Kt)
i = [1]
[I,J] = Kt.shape
print(I)
print(J)

In [ ]:
index = np.array(range(J))
index[i] = -1
index

ind_t = i
sum_dist = np.zeros((1, J), np.complex128)
sum_dist

In [ ]:
np.random.random((noc, len(U)))

In [ ]:
result = Kt**2
result

In [ ]:
Kt2 = np.sum(Kt**2, axis=0)
print(Kt2)


In [ ]:
Kq = np.dot(Kt[:, i[0]], Kt)
Kq

In [ ]:
np.lib.scimath.sqrt(Kt2 - 2 * Kq + Kt2[i[0]])

In [ ]:
sum_dist -= np.lib.scimath.sqrt(Kt2 - 2 * Kq + Kt2[i[0]])
sum_dist

In [ ]:
index[i[0]] = i[0]
index

In [ ]:
i = i[1:]
i

In [ ]:
index

In [ ]:
t = np.where(index != 3)[0]
t

In [ ]:
Kt[:, ind_t].T

In [ ]:
Kq = np.dot(Kt[:, ind_t].T, Kt)
Kq

In [ ]:
np.dot(np.ones((noc, 1)), np.mat(np.sum(S, axis=0)))

In [ ]:
np.ones((noc, 1))

In [ ]:
np.sum(S, axis=0)

In [ ]:
np.mat(np.sum(S, axis=0))

In [ ]:
ind

In [ ]:
S

In [ ]:
np.sum(S, axis=0)

In [ ]:
np.sum(S, axis=1)

In [ ]:
l = [1,9,3,4,5,6]
max(zip(range(len(l)),l), key = lambda x:x[1])

In [ ]:
sum_dist

In [ ]:
index

In [ ]:
t = np.where(index != -1)[0]
t

In [ ]:
sum_dist = np.zeros((1,5), np.complex128)
sum_dist[0][0] += 2
sum_dist[0][4] += 5

print(sum_dist)
sum_dist[:,[2,3,4]][0].real


In [ ]:
index = np.array([0,2,-1,4,5])

In [ ]:
i = 2
i

In [ ]:
t = np.where(index != -1)[0]

In [ ]:
sum_dist

In [ ]:
max(sum_dist[:,[0,1,3,4]][0].real)

In [ ]:
vals

In [ ]:
print(pd.__version__)

In [ ]:
dec6_wo_st = dec6[['positive','negative','totalTestResults','recovered', 'death']]
dec6_wo_st = dec6_wo_st.to_numpy()
dec6_wo_st

In [ ]:
XC, S, C, SSE, varexpl = PCHA(dec6_wo_st, noc=3, I = None, delta=0.1)

In [ ]:
S

In [ ]:
XC.shape

In [ ]:
varexpl

In [ ]:
C

In [ ]:
def furthest_sum(K, noc, i, exclude=[]):
    
    def max_ind_val(l):
        return max(zip(range(len(l)), l), key=lambda x: x[1])
    
    I, J = K.shape
    index = np.array(range(J))
    index[exclude] = 0
    index[i] = -1
    ind_t = i
    sum_dist = np.zeros((1, J), np.complex128)

    if J > noc * I:
        Kt = K
        Kt2 = np.sum(Kt**2, axis=0)
        for k in range(1, noc + 11):
            if k > noc - 1:
                Kq = np.dot(Kt[:, i[0]], Kt)
                sum_dist -= np.lib.scimath.sqrt(Kt2 - 2 * Kq + Kt2[i[0]])
                index[i[0]] = i[0]
                i = i[1:]
            t = np.where(index != -1)[0]
            Kq = np.dot(Kt[:, ind_t].T, Kt)
            sum_dist += np.lib.scimath.sqrt(Kt2 - 2 * Kq + Kt2[ind_t])
            ind, val = max_ind_val(sum_dist[:, t][0].real)
            ind_t = t[ind]
            i.append(ind_t)
            index[ind_t] = -1
    else:
        if I != J or np.sum(K - K.T) != 0:  # Generate kernel if K not one
            Kt = K
            K = np.dot(Kt.T, Kt)
            K = np.lib.scimath.sqrt(
                repmat(np.diag(K), J, 1) - 2 * K + \
                repmat(np.mat(np.diag(K)).T, 1, J)
            )

        Kt2 = np.diag(K)  # Horizontal
        for k in range(1, noc + 11):
            if k > noc - 1:
                sum_dist -= np.lib.scimath.sqrt(Kt2 - 2 * K[i[0], :] + Kt2[i[0]])
                index[i[0]] = i[0]
                i = i[1:]
            t = np.where(index != -1)[0]
            sum_dist += np.lib.scimath.sqrt(Kt2 - 2 * K[ind_t, :] + Kt2[ind_t])
            ind, val = max_ind_val(sum_dist[:, t][0].real)
            ind_t = t[ind]
            i.append(ind_t)
            index[ind_t] = -1

    return i


In [ ]:
"""Principal Convex Hull Analysis (PCHA) / Archetypal Analysis."""

import numpy as np
from scipy.sparse import csr_matrix
from datetime import datetime as dt
import time

from py_pcha.furthest_sum import furthest_sum


def PCHAm(X, noc, I=None, U=None, delta=0, verbose=False, conv_crit=1E-6, maxiter=500):
    """Return archetypes of dataset.
    Note: Commonly data is formatted to have shape (examples, dimensions).
    This function takes input and returns output of the transposed shape,
    (dimensions, examples).
    Parameters
    ----------
    X : numpy.2darray
        Data matrix in which to find archetypes
    noc : int
        Number of archetypes to find
    I : 1d-array
        Entries of X to use for dictionary in C (optional)
    U : 1d-array
        Entries of X to model in S (optional)
    Output
    ------
    XC : numpy.2darray
        I x noc feature matrix (i.e. XC=X[:,I]*C forming the archetypes)
    S : numpy.2darray
        noc x length(U) matrix, S>=0 |S_j|_1=1
    C : numpy.2darray
        noc x length(U) matrix, S>=0 |S_j|_1=1
    SSE : float
        Sum of Squared Errors
    varexlp : float
        Percent variation explained by the model
    """
    def S_update(S, XCtX, CtXtXC, muS, SST, SSE, niter):
        """Update S for one iteration of the algorithm."""
        noc, J = S.shape
        e = np.ones((noc, 1))
        for k in range(niter):
            SSE_old = SSE
            g = (np.dot(CtXtXC, S) - XCtX) / (SST / J)
            g = g - e * np.sum(g.A * S.A, axis=0)

            S_old = S
            while True:
                S = (S_old - g * muS).clip(min=0)
                S = S / np.dot(e, np.sum(S, axis=0))
                SSt = S * S.T
                SSE = SST - 2 * np.sum(XCtX.A * S.A) + np.sum(CtXtXC.A * SSt.A)
                if SSE <= SSE_old * (1 + 1e-9):
                    muS = muS * 1.2
                    break
                else:
                    muS = muS / 2

        return S, SSE, muS, SSt

    def C_update(X, XSt, XC, SSt, C, delta, muC, mualpha, SST, SSE, niter=1):
        """Update C for one iteration of the algorithm."""
        J, nos = C.shape

        if delta != 0:
            alphaC = np.sum(C, axis=0).A[0]
            C = np.dot(C, np.diag(1 / alphaC))

        e = np.ones((J, 1))
        XtXSt = np.dot(X.T, XSt)

        for k in range(niter):

            # Update C
            SSE_old = SSE
            g = (np.dot(X.T, np.dot(XC, SSt)) - XtXSt) / SST

            if delta != 0:
                g = np.dot(g, np.diag(alphaC))
            g = g.A - e * np.sum(g.A * C.A, axis=0)

            C_old = C
            while True:
                C = (C_old - muC * g).clip(min=0)
                nC = np.sum(C, axis=0) + np.finfo(float).eps
                C = np.dot(C, np.diag(1 / nC.A[0]))

                if delta != 0:
                    Ct = C * np.diag(alphaC)
                else:
                    Ct = C

                XC = np.dot(X, Ct)
                CtXtXC = np.dot(XC.T, XC)
                SSE = SST - 2 * np.sum(XC.A * XSt.A) + np.sum(CtXtXC.A * SSt.A)

                if SSE <= SSE_old * (1 + 1e-9):
                    muC = muC * 1.2
                    break
                else:
                    muC = muC / 2

            # Update alphaC
            SSE_old = SSE
            if delta != 0:
                g = (np.diag(CtXtXC * SSt).T / alphaC - np.sum(C.A * XtXSt.A)) / (SST * J)
                alphaC_old = alphaC
                while True:
                    alphaC = alphaC_old - mualpha * g
                    alphaC[alphaC < 1 - delta] = 1 - delta
                    alphaC[alphaC > 1 + delta] = 1 + delta

                    XCt = np.dot(XC, np.diag(alphaC / alphaC_old))
                    CtXtXC = np.dot(XCt.T, XCt)
                    SSE = SST - 2 * np.sum(XCt.A * XSt.A) + np.sum(CtXtXC.A * SSt.A)

                    if SSE <= SSE_old * (1 + 1e-9):
                        mualpha = mualpha * 1.2
                        XC = XCt
                        break
                    else:
                        mualpha = mualpha / 2

        if delta != 0:
            C = C * np.diag(alphaC)

        return C, SSE, muC, mualpha, CtXtXC, XC

    N, M = X.shape
    

    if I is None:
        I = range(M)
    if U is None:
        U = range(M)

    SST = np.sum(X[:, U] * X[:, U])

    # Initialize C
    try:
        i = furthest_sum(X[:, I], noc, [int(np.ceil(len(I) * np.random.rand()))])
    except IndexError:
        class InitializationException(Exception): pass
        raise InitializationException("Initialization does not converge. Too few examples in dataset.")

    j = range(noc)
    C = csr_matrix((np.ones(len(i)), (i, j)), shape=(len(I), noc)).todense()
    print(C)
    
    XC = np.dot(X[:, I], C)

    muS, muC, mualpha = 1, 1, 1

    # Initialise S
    XCtX = np.dot(XC.T, X[:, U])
    CtXtXC = np.dot(XC.T, XC)
    S = -np.log(np.random.random((noc, len(U))))
    S = S / np.dot(np.ones((noc, 1)), np.mat(np.sum(S, axis=0)))
    SSt = np.dot(S, S.T)
    SSE = SST - 2 * np.sum(XCtX.A * S.A) + np.sum(CtXtXC.A * SSt.A)
    S, SSE, muS, SSt = S_update(S, XCtX, CtXtXC, muS, SST, SSE, 25)

    # Set PCHA parameters
    iter_ = 0
    dSSE = np.inf
    t1 = dt.now()
    varexpl = (SST - SSE) / SST

    if verbose:
        print('\nPrincipal Convex Hull Analysis / Archetypal Analysis')
        print('A ' + str(noc) + ' component model will be fitted')
        print('To stop algorithm press control C\n')

    dheader = '%10s | %10s | %10s | %10s | %10s | %10s | %10s | %10s' % ('Iteration', 'Expl. var.', 'Cost func.', 'Delta SSEf.', 'muC', 'mualpha', 'muS', ' Time(s)   ')
    dline = '-----------+------------+------------+-------------+------------+------------+------------+------------+'

    while np.abs(dSSE) >= conv_crit * np.abs(SSE) and iter_ < maxiter and varexpl < 0.9999:
        if verbose and iter_ % 100 == 0:
            print(dline)
            print(dheader)
            print(dline)
        told = t1
        iter_ += 1
        SSE_old = SSE

        # C (and alpha) update
        XSt = np.dot(X[:, U], S.T)
        C, SSE, muC, mualpha, CtXtXC, XC = C_update(
            X[:, I], XSt, XC, SSt, C, delta, muC, mualpha, SST, SSE, 10
        )

        # S update
        XCtX = np.dot(XC.T, X[:, U])
        S, SSE, muS, SSt = S_update(
            S, XCtX, CtXtXC, muS, SST, SSE, 10
        )

        # Evaluate and display iteration
        dSSE = SSE_old - SSE
        t1 = dt.now()
        if iter_ % 1 == 0:
            time.sleep(0.000001)
            varexpl = (SST - SSE) / SST
            if verbose:
                print('%10.0f | %10.4f | %10.4e | %10.4e | %10.4e | %10.4e | %10.4e | %10.4f \n' % (iter_, varexpl, SSE, dSSE/np.abs(SSE), muC, mualpha, muS, (t1-told).seconds))

    # Display final iteration
    varexpl = (SST - SSE) / SST
    if verbose:
        print(dline)
        print(dline)
        print('%10.0f | %10.4f | %10.4e | %10.4e | %10.4e | %10.4e | %10.4e | %10.4f \n' % (iter_, varexpl, SSE, dSSE/np.abs(SSE), muC, mualpha, muS, (t1-told).seconds))

    print(S)
    print(C)
    print(XC)
        
    # Sort components according to importance
    ind, vals = zip(
        *sorted(enumerate(np.sum(S, axis=1)), key=lambda x: x[0], reverse=1)
    )
    S = S[ind, :]
    C = C[:, ind]
    XC = XC[:, ind]

    return XC, S, C, SSE, varexpl

In [ ]:
XC2, S2, C2, SSE2, varexpl2 = PCHAm(dec6_wo_st, noc=3, I = None, delta=0.1)


In [ ]:
XC2

In [ ]:
C2

In [ ]:
C2[:,0]

In [ ]:
XC2

In [ ]:
ans = 0

for i in range(len(XC)):
    a = XC[i] - XC2[i]
    ans = ans + a
    
print(ans)

In [ ]:
ans = 0

for i in range(len(S)):
    a = S[i] - S2[i]
    ans = ans + a
    
print(ans)

In [ ]:
ans = 0

for i in range(len(C)):
    a = C[i] - C2[i]
    ans = ans + a
    
print(ans)

Attempts to understand

In [ ]:
#dimensions = 7
#examples = 2
#X = np.random.random((dimensions, examples)) * 10
I_list = ['rd','be','gn','bl','cf','dg','co','pi','yu','we','oi','or','mq','mt','nz']

a = [[5, 0],[5, 1],[10 ,1],[2, 4],[6, 1],
     [0, 1],[1, 7],[3,1],[3,2],[3,3],
     [4,1],[2,2],[2,3],[3,5],[7,1]]
a

arr_a = np.array(a)

x = arr_a[:,0]
y = arr_a[:,1]
print(x)
print(y)
plt.scatter(x,y)

In [ ]:
XC, S, C, SSE, varexpl = PCHA(arr_a, noc=2, I = None, delta=0.1)

In [ ]:
XC

In [ ]:
S

In [ ]:
C

In [ ]:
SSE

In [ ]:
varexpl

In [ ]:
XC*C