In [1]:
import pandas as pd
import numpy as np
import py_pcha
from py_pcha import PCHA
import matplotlib.pyplot as plt
from numpy.matlib import repmat

In [2]:
import pixiedust

Pixiedust database opened successfully


In [ ]:
from pip._internal import main
main(["install", "msgpack"])
main(["install", "pixiedust"])

In [ ]:
pip install --upgrade ipython

In [3]:
data=pd.read_csv("/Users/markomiholjcic/Documents/GitHub/ArchetypalAnalysis/data/us_states_covid19_daily.csv")
data

date state  positive  probableCases   negative  pending  \
0      20201206    AK   35720.0            NaN  1042056.0      NaN   
1      20201206    AL  269877.0        45962.0  1421126.0      NaN   
2      20201206    AR  170924.0        22753.0  1614979.0      NaN   
3      20201206    AS       0.0            NaN     2140.0      NaN   
4      20201206    AZ  364276.0        12590.0  2018813.0      NaN   
...         ...   ...       ...            ...        ...      ...   
15628  20200124    WA       0.0            NaN        0.0      NaN   
15629  20200123    MA       NaN            NaN        NaN      NaN   
15630  20200123    WA       0.0            NaN        0.0      NaN   
15631  20200122    MA       NaN            NaN        NaN      NaN   
15632  20200122    WA       0.0            NaN        0.0      NaN   

         totalTestResultsSource  totalTestResults  hospitalizedCurrently  \
0               totalTestsViral         1077776.0                  164.0   
1         totalTestsPeopleViral         1645041.0                 1927.0   
2               totalTestsViral         1763150.0                 1076.0   
3               totalTestsViral            2140.0                    NaN   
4         totalTestsPeopleViral         2370499.0                 2977.0   
...                         ...               ...                    ...   
15628  totalTestEncountersViral               0.0                    NaN   
15629           totalTestsViral               2.0                    NaN   
15630  totalTestEncountersViral               0.0                    NaN   
15631           totalTestsViral               1.0                    NaN   
15632  totalTestEncountersViral               0.0                    NaN   

       hospitalizedCumulative  ...   posNeg  deathIncrease  \
0                       799.0  ...  1077776              0   
1                     26331.0  ...  1691003             12   
2                      9401.0  ...  1785903             40   
3                         NaN  ...     2140              0   
4                     28248.0  ...  2383089             25   
...                       ...  ...      ...            ...   
15628                     NaN  ...        0              0   
15629                     NaN  ...        0              0   
15630                     NaN  ...        0              0   
15631                     NaN  ...        0              0   
15632                     NaN  ...        0              0   

       hospitalizedIncrease                                      hash  \
0                         0  7b1d31e2756687bb9259b29195f1db6cdb321ea6   
1                         0  19454ed8fe28fc0a7948fc0771b2f3c846c1c92e   
2                        21  25fc83bffff5b32ba1a737be8e087fad9f4fde33   
3                         0  8c39eec317586b0c34fc2903e6a3891ecb00469e   
4                       242  7cf59da9e4bc31d905e179211313d08879880a85   
...                     ...                                       ...   
15628                     0  82726df68eb97c98a4a6ee792349e547023147d5   
15629                     0  76bc987d054b119a4e05a4a43742249c0b0568b6   
15630                     0  1c2229c239ffad5e5fdd9d76c641dc9166caf6ba   
15631                     0  01f5dcd6631859503ef1b62d81d49e41d12fc1bd   
15632                     0  4502685e582e68071bfe8f7e1b307bc09c16728d   

       commercialScore negativeRegularScore negativeScore positiveScore score  \
0                    0                    0             0             0     0   
1                    0                    0             0             0     0   
2                    0                    0             0             0     0   
3                    0                    0             0             0     0   
4                    0                    0             0             0     0   
...                ...                  ...           ...           ...   ...   
15628                0                    0             0           

In [ ]:
data=pd.read_csv("/Users/u0984549/Documents/GitHub/ArchetypalAnalysis/data/us_states_covid19_daily.csv")
data

Data for 50 states, DC, and 5 territories on December 6, 2020. Select states and territories with missing values were removed. 

In [4]:
dec6 = data.loc[data['date'] == 20201206]
dec6 = dec6[['positive','negative','totalTestResults','recovered', 'death']]
dec6 = dec6.dropna()
dec6

positive    negative  totalTestResults  recovered    death
0     35720.0   1042056.0         1077776.0     7165.0    143.0
1    269877.0   1421126.0         1645041.0   168387.0   3889.0
2    170924.0   1614979.0         1763150.0   149490.0   2660.0
4    364276.0   2018813.0         2370499.0    56382.0   6950.0
6    260581.0   1608829.0         3478160.0    13941.0   2724.0
7    127715.0   3294383.0         3422098.0     9800.0   5146.0
8     23136.0    711497.0          734633.0    16665.0    697.0
9     39912.0    400854.0          778298.0    18851.0    793.0
12     7004.0     79571.0           86575.0     6056.0    113.0
13    18842.0    295153.0          701776.0    11958.0    262.0
14   213390.0    885199.0         1098589.0   159063.0   2683.0
15   109705.0    398027.0          490387.0    42932.0   1032.0
17   381617.0   1928262.0         4577211.0   224059.0   6242.0
18   168295.0    676891.0          845186.0     3615.0   1786.0
19   200632.0   2568543.0         2732005.0    30161.0   2072.0
20   251123.0   3356960.0         3608083.0   202891.0   6584.0
21   256844.0   3250728.0         8970252.0   169809.0  11004.0
22   215027.0   2225595.0         4685476.0     8785.0   4846.0
23    13348.0    900832.0          914180.0    10080.0    227.0
24   426576.0   6538482.0         6965058.0   197750.0  10321.0
25   350862.0   2301135.0         4431677.0   308218.0   3984.0
27      106.0     17010.0           17116.0       29.0      2.0
28   164931.0    982395.0         1147326.0   128746.0   3961.0
29    67875.0    620339.0          688214.0    50287.0    736.0
30   394990.0   5216286.0         5611276.0   315979.0   5543.0
31    82981.0    274492.0         1132025.0    76999.0   1019.0
32   138568.0    631739.0         1456368.0    69840.0   1194.0
33    24771.0    415976.0          861473.0    19553.0    564.0
34   368016.0   5918797.0         6286813.0    46021.0  17321.0
35   108088.0   1539888.0         1647976.0    37041.0   1749.0
37   705827.0  19888867.0        20594694.0    87949.0  27149.0
38   475024.0   6000686.0         6475710.0   321505.0   6959.0
39   216486.0   2008829.0         2225315.0   182942.0   1896.0
40    84496.0   2005617.0         2090113.0     5870.0   1033.0
41   420114.0   2929036.0         3349150.0   238660.0  11331.0
42    56671.0    305972.0          362643.0    47406.0   1192.0
43    62137.0    482922.0         1608848.0     3939.0   1413.0
44   232099.0   2296092.0         2528191.0   119844.0   4566.0
45    85991.0    254004.0          339995.0    68449.0   1110.0
46   400594.0   4289928.0         4690522.0   360152.0   4943.0
47  1249323.0  10111653.0        11360976.0  1030716.0  22594.0
48   215407.0   1180321.0         1922236.0   153027.0    939.0
49   255053.0   3268822.0         3492201.0    25235.0   4200.0
50     1633.0     27660.0           29293.0     1513.0     23.0
51     5015.0    228865.0          583802.0     2951.0     79.0
53   441067.0   2196722.0         4623227.0   348995.0   3952.0
54    54997.0   1168366.0         1223363.0    35082.0    838.0
55    36317.0    144576.0          417627.0    29656.0    257.0

In [ ]:
dec6.to_csv('/Users/markomiholjcic/Documents/GitHub/ArchetypalAnalysis/data/COVID19.csv', index = False)

In [ ]:
dec6.to_csv('/Users/u0984549/Documents/GitHub/ArchetypalAnalysis/data/COVID19.csv', index = False)

In [ ]:
U = np.array([1,2,3])
X = np.array([[2,3,4,5], [5,6,7,8], [1,4,5,6]])

print(X)
print(X.T)

#(X[:, U] * X[:, U])

In [ ]:
np.dot(X, X.T)

In [ ]:
repmat(np.mat(np.diag(X)).T, 1, 5)

In [ ]:
repmat(np.mat(np.diag(X)), 5, 1)

In [ ]:
int(np.ceil(5 * np.random.rand()))

In [ ]:
len(range(0,5))

In [ ]:
np.array(range(5))

In [ ]:
t = np.diag(X)
print(t)
np.where(t != 2)[0]

In [ ]:
repmat(np.diag(X), 5, 1)

In [ ]:
X[:,U]*X[:,U]

In [ ]:
ind_t = 2
ind_t[0]

In [ ]:
X

In [ ]:
X[[ind_t],:] * X[ind_t]

In [ ]:
np(X + X[ind_t])

In [ ]:
np.lib.scimath.sqrt(X + X[ind_t])

In [ ]:
Kt = np.array([[1,2], [5,6], [8,9]])
Kt = pd.DataFrame(Kt)
Kt.to_csv('/Users/markomiholjcic/Documents/GitHub/ArchetypalAnalysis/data/small.csv', index = False)

In [ ]:
e = np.ones((4, 1))
e

In [ ]:
CtXtXC = [2,3]
S = [3,4]
XCtX = [1,1]
SST = 5
J = 5
g = (np.dot(CtXtXC, S) - XCtX) / (SST / J)
g

In [ ]:
a = np.arange(10)
a.clip(min=5)

In [ ]:
a = range(2)
print(a)

In [ ]:
X = np.matrix([[1, 2, 3],
    [4, 5, 6], [7,8,9]])
U = [0,1,2]
print(U)
print(X)
print(X[:, U])

In [ ]:
np.sum(np.multiply(X[:, U],X[:, U]))

In [ ]:
[int(np.ceil(len(U) * np.random.rand()))]

In [ ]:
noc = 3
I = [1,2]
i = [3]
j = 3

In [ ]:
len(I)

In [ ]:
Kt = np.array([[1,2], [5,6], [8,9]])
print(Kt)
i = [1]
[I,J] = Kt.shape
print(I)
print(J)

In [ ]:
index = np.array(range(J))
index[i] = -1
index

ind_t = i
sum_dist = np.zeros((1, J), np.complex128)
sum_dist

In [ ]:
np.random.random((noc, len(U)))

In [ ]:
result = Kt**2
result

In [ ]:
Kt2 = np.sum(Kt**2, axis=0)
print(Kt2)


In [ ]:
Kq = np.dot(Kt[:, i[0]], Kt)
Kq

In [ ]:
np.lib.scimath.sqrt(Kt2 - 2 * Kq + Kt2[i[0]])

In [ ]:
sum_dist -= np.lib.scimath.sqrt(Kt2 - 2 * Kq + Kt2[i[0]])
sum_dist

In [ ]:
index[i[0]] = i[0]
index

In [ ]:
i = i[1:]
i

In [ ]:
index

In [ ]:
t = np.where(index != 3)[0]
t

In [ ]:
Kt[:, ind_t].T

In [ ]:
Kq = np.dot(Kt[:, ind_t].T, Kt)
Kq

In [ ]:
np.dot(np.ones((noc, 1)), np.mat(np.sum(S, axis=0)))

In [ ]:
np.ones((noc, 1))

In [ ]:
np.sum(S, axis=0)

In [ ]:
np.mat(np.sum(S, axis=0))

In [ ]:
ind

In [ ]:
S

In [ ]:
np.sum(S, axis=0)

In [ ]:
np.sum(S, axis=1)

In [ ]:
l = [1,9,3,4,5,6]
max(zip(range(len(l)),l), key = lambda x:x[1])

In [ ]:
sum_dist

In [ ]:
index

In [ ]:
t = np.where(index != -1)[0]
t

In [ ]:
sum_dist = np.zeros((1,5), np.complex128)
sum_dist[0][0] += 2
sum_dist[0][4] += 5

print(sum_dist)
sum_dist[:,[2,3,4]][0].real


In [ ]:
index = np.array([0,2,-1,4,5])

In [ ]:
i = 2
i

In [ ]:
t = np.where(index != -1)[0]

In [ ]:
sum_dist

In [ ]:
max(sum_dist[:,[0,1,3,4]][0].real)

In [ ]:
vals

In [ ]:
print(pd.__version__)

In [ ]:
from scipy.sparse import csr_matrix

In [ ]:
j = [0,1,2]

In [ ]:
i = [1,2,0]

In [ ]:
csr_matrix((np.ones(len(i)), (i, j)), shape=(5, 3)).todense()

In [ ]:
U

In [ ]:
np.log(np.random.random((3, len(U))))

In [ ]:
X = np.ones((3, 5))*2
S = np.ones((3, 5))*8
g = S*X
g

In [ ]:
np.sum(XCtX.A * S.A)

In [ ]:
e = np.ones((5, 1))
e is array

In [ ]:
r = np.sum(g * g, axis=0)
r.shape

In [ ]:
e * np.sum(g * g, axis=0)

In [5]:
dec6_wo_st = dec6[['positive','negative','totalTestResults','recovered', 'death']]
dec6_wo_st = dec6_wo_st.to_numpy()
dec6_wo_st

array([[3.5720000e+04, 1.0420560e+06, 1.0777760e+06, 7.1650000e+03,
        1.4300000e+02],
       [2.6987700e+05, 1.4211260e+06, 1.6450410e+06, 1.6838700e+05,
        3.8890000e+03],
       [1.7092400e+05, 1.6149790e+06, 1.7631500e+06, 1.4949000e+05,
        2.6600000e+03],
       [3.6427600e+05, 2.0188130e+06, 2.3704990e+06, 5.6382000e+04,
        6.9500000e+03],
       [2.6058100e+05, 1.6088290e+06, 3.4781600e+06, 1.3941000e+04,
        2.7240000e+03],
       [1.2771500e+05, 3.2943830e+06, 3.4220980e+06, 9.8000000e+03,
        5.1460000e+03],
       [2.3136000e+04, 7.1149700e+05, 7.3463300e+05, 1.6665000e+04,
        6.9700000e+02],
       [3.9912000e+04, 4.0085400e+05, 7.7829800e+05, 1.8851000e+04,
        7.9300000e+02],
       [7.0040000e+03, 7.9571000e+04, 8.6575000e+04, 6.0560000e+03,
        1.1300000e+02],
       [1.8842000e+04, 2.9515300e+05, 7.0177600e+05, 1.1958000e+04,
        2.6200000e+02],
       [2.1339000e+05, 8.8519900e+05, 1.0985890e+06, 1.5906300e+05,
        2.68

In [ ]:
XC, S, C, SSE, varexpl = PCHA(dec6_wo_st, noc=3, I = None, delta=0.1)

In [ ]:
XC

In [ ]:
np.random.random((3,5))

In [ ]:
np.ones((3,5))-0.5

In [6]:
def furthest_sum(K, noc, i, exclude=[]):
    
    def max_ind_val(l):
        return max(zip(range(len(l)), l), key=lambda x: x[1])
    
    I, J = K.shape
    index = np.array(range(J))
    index[exclude] = 0
    index[i] = -1
    ind_t = i
    sum_dist = np.zeros((1, J), np.complex128)

    if J > noc * I:
        Kt = K
        Kt2 = np.sum(Kt**2, axis=0)
        for k in range(1, noc + 11):
            if k > noc - 1:
                Kq = np.dot(Kt[:, i[0]], Kt)
                sum_dist -= np.lib.scimath.sqrt(Kt2 - 2 * Kq + Kt2[i[0]])
                index[i[0]] = i[0]
                i = i[1:]
            t = np.where(index != -1)[0]
            Kq = np.dot(Kt[:, ind_t].T, Kt)
            sum_dist += np.lib.scimath.sqrt(Kt2 - 2 * Kq + Kt2[ind_t])
            ind, val = max_ind_val(sum_dist[:, t][0].real)
            ind_t = t[ind]
            i.append(ind_t)
            index[ind_t] = -1
    else:
        if I != J or np.sum(K - K.T) != 0:  # Generate kernel if K not one
            Kt = K
            K = np.dot(Kt.T, Kt)
            K = np.lib.scimath.sqrt(
                repmat(np.diag(K), J, 1) - 2 * K + \
                repmat(np.mat(np.diag(K)).T, 1, J)
            )

        Kt2 = np.diag(K)  # Horizontal
        for k in range(1, noc + 11):
            if k > noc - 1:
                sum_dist -= np.lib.scimath.sqrt(Kt2 - 2 * K[i[0], :] + Kt2[i[0]])
                index[i[0]] = i[0]
                i = i[1:]
            t = np.where(index != -1)[0]
            sum_dist += np.lib.scimath.sqrt(Kt2 - 2 * K[ind_t, :] + Kt2[ind_t])
            ind, val = max_ind_val(sum_dist[:, t][0].real)
            ind_t = t[ind]
            i.append(ind_t)
            index[ind_t] = -1

    return i


In [ ]:
import pixiedust

In [ ]:
pixiedust

In [ ]:
%%pixie_debugger

In [51]:
i = np.array([0,1,2])
i

array([0, 1, 2])

In [58]:
"""Principal Convex Hull Analysis (PCHA) / Archetypal Analysis."""

import numpy as np
from scipy.sparse import csr_matrix
from datetime import datetime as dt
import time

#from py_pcha.furthest_sum import furthest_sum


def PCHAm(X, noc, I=None, U=None, delta=0, verbose=False, conv_crit=1E-6, maxiter=500):
    """Return archetypes of dataset.
    Note: Commonly data is formatted to have shape (examples, dimensions).
    This function takes input and returns output of the transposed shape,
    (dimensions, examples).
    Parameters
    ----------
    X : numpy.2darray
        Data matrix in which to find archetypes
    noc : int
        Number of archetypes to find
    I : 1d-array
        Entries of X to use for dictionary in C (optional)
    U : 1d-array
        Entries of X to model in S (optional)
    Output
    ------
    XC : numpy.2darray
        I x noc feature matrix (i.e. XC=X[:,I]*C forming the archetypes)
    S : numpy.2darray
        noc x length(U) matrix, S>=0 |S_j|_1=1
    C : numpy.2darray
        noc x length(U) matrix, S>=0 |S_j|_1=1
    SSE : float
        Sum of Squared Errors
    varexlp : float
        Percent variation explained by the model
    """
    def S_update(S, XCtX, CtXtXC, muS, SST, SSE, niter):
        """Update S for one iteration of the algorithm."""
        noc, J = S.shape
        e = np.ones((noc, 1))
        #print(e.ndim)
        for k in range(niter):
            SSE_old = SSE
            #print(SSE_old)
            g = (np.dot(CtXtXC, S) - XCtX) / (SST / J)
            #print(g)
            g = g - e * np.sum(g.A * S.A, axis=0)
            #print(g)

            S_old = S
            #print(S_old)
            while True:
                S = (S_old - g * muS).clip(min=0)
                S = S / np.dot(e, np.sum(S, axis=0))
                #print(S)
                SSt = S * S.T
                #print(SSt)
                SSE = SST - 2 * np.sum(XCtX.A * S.A) + np.sum(CtXtXC.A * SSt.A)
                #print(SSE)
                #print(SSE_old)
                if SSE <= SSE_old * (1 + 1e-9):
                    muS = muS * 1.2
                    #print(muS)
                    break
                else:
                    muS = muS / 2

        return S, SSE, muS, SSt

    def C_update(X, XSt, XC, SSt, C, delta, muC, mualpha, SST, SSE, niter=1):
        """Update C for one iteration of the algorithm."""
        J, nos = C.shape

        if delta != 0:
            alphaC = np.sum(C, axis=0).A[0]
            C = np.dot(C, np.diag(1 / alphaC))

        e = np.ones((J, 1))
        XtXSt = np.dot(X.T, XSt)
        #print(XtXSt)

        for k in range(niter):

            # Update C
            SSE_old = SSE
            g = (np.dot(X.T, np.dot(XC, SSt)) - XtXSt) / SST

            if delta != 0:
                g = np.dot(g, np.diag(alphaC))
            g = g.A - e * np.sum(g.A * C.A, axis=0)

            C_old = C
            while True:
                C = (C_old - muC * g).clip(min=0)
                nC = np.sum(C, axis=0) + np.finfo(float).eps
                C = np.dot(C, np.diag(1 / nC.A[0]))

                if delta != 0:
                    Ct = C * np.diag(alphaC)
                else:
                    Ct = C

                XC = np.dot(X, Ct)
                CtXtXC = np.dot(XC.T, XC)
                SSE = SST - 2 * np.sum(XC.A * XSt.A) + np.sum(CtXtXC.A * SSt.A)

                if SSE <= SSE_old * (1 + 1e-9):
                    muC = muC * 1.2
                    break
                else:
                    muC = muC / 2

            # Update alphaC
            SSE_old = SSE
            if delta != 0:
                g = (np.diag(CtXtXC * SSt).T / alphaC - np.sum(C.A * XtXSt.A)) / (SST * J)
                alphaC_old = alphaC
                while True:
                    alphaC = alphaC_old - mualpha * g
                    alphaC[alphaC < 1 - delta] = 1 - delta
                    alphaC[alphaC > 1 + delta] = 1 + delta

                    XCt = np.dot(XC, np.diag(alphaC / alphaC_old))
                    CtXtXC = np.dot(XCt.T, XCt)
                    SSE = SST - 2 * np.sum(XCt.A * XSt.A) + np.sum(CtXtXC.A * SSt.A)

                    if SSE <= SSE_old * (1 + 1e-9):
                        mualpha = mualpha * 1.2
                        XC = XCt
                        break
                    else:
                        mualpha = mualpha / 2

        if delta != 0:
            C = C * np.diag(alphaC)

        return C, SSE, muC, mualpha, CtXtXC, XC

    N, M = X.shape
    

    if I is None:
        I = range(M)
    if U is None:
        U = range(M)
        
    #print(X[:,U])

    SST = np.sum(X[:, U] * X[:, U])
    #print(SST)
    
    #print(X[:,I])

    # Initialize C
    #try:
        #i = furthest_sum(X[:, I], noc, [int(np.ceil(len(I) * np.random.rand()))])
    #except IndexError:
    #    class InitializationException(Exception): pass
    #    raise InitializationException("Initialization does not converge. Too few examples in dataset.")

    i = [1,2,0]
        
    j = range(noc)
    C = csr_matrix((np.ones(len(i)), (i, j)), shape=(len(I), noc)).todense()
    #print(C)
    
    XC = np.dot(X[:, I], C)
    #print(XC)

    muS, muC, mualpha = 1, 1, 1

    # Initialise S
    XCtX = np.dot(XC.T, X[:, U])
    #print(XCtX)
    CtXtXC = np.dot(XC.T, XC)
    #print(CtXtXC)
    #S = -np.log(np.random.random((noc, len(U))))
    S = -np.log((np.ones((3,5))-0.5))
    #print(S)
    S = S / np.dot(np.ones((noc, 1)), np.mat(np.sum(S, axis=0)))
    #print(S)
    SSt = np.dot(S, S.T)
    SSE = SST - 2 * np.sum(XCtX.A * S.A) + np.sum(CtXtXC.A * SSt.A)
    #print(SSE)
    S, SSE, muS, SSt = S_update(S, XCtX, CtXtXC, muS, SST, SSE, 25)
    #print(S, SSE, muS, SSt)

    # Set PCHA parameters
    iter_ = 0
    dSSE = np.inf
    t1 = dt.now()
    varexpl = (SST - SSE) / SST
    #print(varexpl)

    if verbose:
        print('\nPrincipal Convex Hull Analysis / Archetypal Analysis')
        print('A ' + str(noc) + ' component model will be fitted')
        print('To stop algorithm press control C\n')

    dheader = '%10s | %10s | %10s | %10s | %10s | %10s | %10s | %10s' % ('Iteration', 'Expl. var.', 'Cost func.', 'Delta SSEf.', 'muC', 'mualpha', 'muS', ' Time(s)   ')
    dline = '-----------+------------+------------+-------------+------------+------------+------------+------------+'

    while np.abs(dSSE) >= conv_crit * np.abs(SSE) and iter_ < maxiter and varexpl < 0.9999:
        if verbose and iter_ % 100 == 0:
            print(dline)
            print(dheader)
            print(dline)
        told = t1
        iter_ += 1
        SSE_old = SSE

        # C (and alpha) update
        XSt = np.dot(X[:, U], S.T)
        #print(XSt)
        C, SSE, muC, mualpha, CtXtXC, XC = C_update(
            X[:, I], XSt, XC, SSt, C, delta, muC, mualpha, SST, SSE, 10
        )
        #print(C)

        # S update
        XCtX = np.dot(XC.T, X[:, U])
        S, SSE, muS, SSt = S_update(
            S, XCtX, CtXtXC, muS, SST, SSE, 10
        )

        # Evaluate and display iteration
        dSSE = SSE_old - SSE
        #print(dSSE)
        t1 = dt.now()
        if iter_ % 1 == 0:
            time.sleep(0.000001)
            varexpl = (SST - SSE) / SST
            if verbose:
                print('%10.0f | %10.4f | %10.4e | %10.4e | %10.4e | %10.4e | %10.4e | %10.4f \n' % (iter_, varexpl, SSE, dSSE/np.abs(SSE), muC, mualpha, muS, (t1-told).seconds))

    # Display final iteration
    varexpl = (SST - SSE) / SST
    if verbose:
        print(dline)
        print(dline)
        print('%10.0f | %10.4f | %10.4e | %10.4e | %10.4e | %10.4e | %10.4e | %10.4f \n' % (iter_, varexpl, SSE, dSSE/np.abs(SSE), muC, mualpha, muS, (t1-told).seconds))

    #print(S)
    #print(C)
    #print(XC)
        
    # Sort components according to importance
    ind, vals = zip(
        *sorted(enumerate(np.sum(S, axis=1)), key=lambda x: x[0], reverse=1)
    )
    S = S[ind, :]
    C = C[:, ind]
    XC = XC[:, ind]

    return XC, S, C, SSE, varexpl

XC2, S2, C2, SSE2, varexpl2 = PCHAm(dec6_wo_st, noc=3, I = None, delta=0)

[[4.90908248e+13 6.07625850e+13 7.37404729e+12]
 [7.53451718e+14 8.77577122e+14 7.74021307e+13]
 [8.42019782e+14 1.03696103e+15 9.28733934e+13]
 [2.43808237e+13 3.10989829e+13 4.84010231e+12]
 [1.23149429e+12 1.48702915e+12 1.45040833e+11]]
[[4.96257729e+13 6.02334015e+13 7.36828271e+12]
 [7.61783186e+14 8.69249761e+14 7.73980236e+13]
 [8.51186603e+14 1.02781509e+15 9.28525153e+13]
 [2.46447140e+13 3.08401837e+13 4.83501112e+12]
 [1.24498634e+12 1.47359136e+12 1.44986573e+11]]
[[4.99247833e+13 6.00415042e+13 7.26116964e+12]
 [7.66337035e+14 8.66056680e+14 7.60372565e+13]
 [8.56238961e+14 1.02433779e+15 9.12774610e+13]
 [2.47946602e+13 3.07509190e+13 4.77432967e+12]
 [1.25242871e+12 1.46853258e+12 1.42602992e+11]]
[[5.00895773e+13 5.99707541e+13 7.16712574e+12]
 [7.68828554e+14 8.64681242e+14 7.49211743e+13]
 [8.59010832e+14 1.02287416e+15 8.99692163e+13]
 [2.48777328e+13 3.07240488e+13 4.71812718e+12]
 [1.25651289e+12 1.46645038e+12 1.40601006e+11]]
[[5.01743542e+13 5.99448056e+13 7.10

[[5.02210888e+13 5.99341783e+13 7.07218999e+12]
 [7.70983579e+14 8.63613194e+14 7.38341975e+13]
 [8.61377347e+14 1.02178781e+15 8.86890506e+13]
 [2.49396210e+13 3.07216070e+13 4.65868082e+12]
 [1.25995090e+12 1.46497800e+12 1.38635373e+11]]


In [46]:
XC2, S2, C2, SSE2, varexpl2 = PCHAm(dec6_wo_st, noc=3, I = None, delta=0)

[[0.         0.9727169  0.00423711 0.         0.        ]
 [0.         0.02598145 0.99576289 0.         0.        ]
 [1.         0.00130165 0.         1.         1.        ]] 5425567788993.25 1.4905658850635772 [[9.46196113e-01 2.94917573e-02 1.26613983e-03]
 [2.94917573e-02 9.92218761e-01 3.38188326e-05]
 [1.26613983e-03 3.38188326e-05 3.00000169e+00]]


In [ ]:
varexpl2

In [ ]:
ans = 0

for i in range(len(XC)):
    a = XC[i] - XC2[i]
    ans = ans + a
    
print(ans)

In [ ]:
ans = 0

for i in range(len(S)):
    a = S[i] - S2[i]
    ans = ans + a
    
print(ans)

In [ ]:
ans = 0

for i in range(len(C)):
    a = C[i] - C2[i]
    ans = ans + a
    
print(ans)